# Site settings
title: Mnpn
email: kattsylt@mnpn.dev
description: >- # this means to ignore newlines until "baseurl:"
  Mnpn's website containing projects and information.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mnpn.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Blinieth
github_username: Mnpn
repository: Mnpn/Website
permalink: "/blog/:title"

# Build settings
markdown: kramdown
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
